django_chater/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

from home.urls import api_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
   # path("workspace/", include("workspace.urls")),
    path("api/home/", include((api_urlpatterns, "api"))),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path("", include("home.urls")),
]

django_chater_v2/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("niema_latwo_admin/", admin.site.urls),
    path("workspace/", include("workspace.urls")),
    path("", include("root.urls")),
]

home/urls.py
from django.urls import path, include
from . import api_views


from rest_framework import routers
from rest_framework_nested import routers

app_name = "home"

router = routers.SimpleRouter()
router.register(r'idea_categories', api_views.IdeaCategoryViewSet)
router.register(r'create_user', api_views.CreateUserView)

ideas_router = routers.NestedSimpleRouter(router, r'idea_categories', lookup="idea_category")
ideas_router.register(r'ideas', api_views.IdeaViewSet)

comments_router = routers.NestedSimpleRouter(ideas_router, r'ideas', lookup="idea")
comments_router.register(r'comments', api_views.IdeaCommentViewSet)

api_urlpatterns = [
    path("", include(router.urls)),
    path("", include(ideas_router.urls)),
    path("", include(comments_router.urls)),

]

root/urls.py
from django.urls import path, include
from . import api_views


from rest_framework import routers
from rest_framework.negotiation import BaseContentNegotiation
from rest_framework_nested import routers

app_name = "root"

urlpatterns = [
]


router = routers.SimpleRouter()
router.register(r'idea_categories', api_views.IdeaCategoryViewSet)
router.register(r'create_user', api_views.CreateUserView)
ideas_router = routers.NestedSimpleRouter(router, r'idea_categories', lookup="idea_category")
ideas_router.register(r'ideas', api_views.IdeaViewSet)

comments_router = routers.NestedSimpleRouter(ideas_router, r'ideas', lookup="idea")
comments_router.register(r'comments', api_views.IdeaCommentViewSet)

api_urlpatterns = [
    path("", include(router.urls)),
    path("", include(ideas_router.urls)),
    path("", include(comments_router.urls)),

]

workspace/urls.py
from django.urls import path, include
from .views import room, Workspace

from rest_framework_nested import routers

app_name = "workspace"

router = routers.SimpleRouter()
router.register(r'workspace', workspace_viewset)

workspace_router = routers.NestedSimplerouter(router, r'workspace', lookup="workspace")
workspace_router.register(r'room', room_viewset)

room_router = routers.NestedSimpleRouter(workspace_router, r'room', lookup="room")
room_router = router.register(r'messages', message_viewset)


api_urlpatterns = [
    path("", include(router.urls)),
    path("", include(workspace_router.urls)),
    path("", include(room_router.urls)),
]

root/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator



def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='deleted')[0]

class IdeaCategory(models.Model):
    title = models.CharField(verbose_name="Category title", max_length=50, unique=True)

    def __str__(self):
        return self.title
    

class IdeaTag(models.Model):
    name = models.CharField(
        max_length=20, 
        unique=True,
        db_index=True,
        validators=[RegexValidator(regex='^[a-zA-Z0-9_]+$', message="Invalid tag name")],
    )

    def __str__(self):
        return self.name
    

class Idea(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=50, unique=True)
    text = models.TextField(unique=True)
    create_date = models.DateTimeField(auto_now_add=True)
    in_progress = models.BooleanField(default=False)

    author = models.ForeignKey(User, on_delete=models.SET(get_sentinel_user), related_name="ideas")
    category = models.ForeignKey(IdeaCategory, related_name="ideas", blank=False, on_delete=models.CASCADE)
    tags = models.ManyToManyField(IdeaTag, related_name="ideas", blank=True)

    def __str__(self):
        return "{}: {}".format(self.author, self.title)
    

    class Meta:
        ordering = ['create_date']



class IdeaComment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.SET(get_sentinel_user), related_name="+")
    text = models.TextField(unique=True)
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}: {}".format(self.author, self.text)
    
    class Meta:
        ordering = ['create_date']


class Question(models.Model):
    author = models.CharField(
        max_length=30,
        validators=[RegexValidator(regex='^[a-zA-Z]+$', message="Invalid tag name")],
        )
    text = models.TextField(unique=True)
    create_date = models.DateTimeField(auto_now_add=True)
    answered = models.BooleanField(default=False)
    

    class Meta:
        ordering = ['create_date']

templates/root/ideas.html
{% extends 'base.html' %}
{% load static %}
{% block head%}
    <link rel="stylesheet" type="text/css" href="{% static "css/root/ideas.css"%}"/>
{% endblock%}

{% block header%}
    <div class="header">
        <button type="button" class="btn btn-outline-secondary">
            <a href="{% url "root:index" %}">Home</a>
        </button>
    </div>

{% endblock %}

{% block main %}


    <div class="main main_container">
        <div class="priority_container">
            <h3 class="priority_container__title"> What's New </h3>
            <div class="ideas">
                {% for whats_new in whats_new_p%}
                    <div class="idea">
                        <h5> {{whats_new.title}} </h5>
                        <p> {{whats_new.text}} </p>
                        <h6> {{whats_new.author}} {{whats_new.send_date.date}} </h6>
                    </div>
                {% endfor %}            
            </div>

        </div>
        {% for priority in priorities%}
            <div class="priority_container">
                <h3 class="priority_container__title" style="color:{{priority.color}}">{{priority.title}}</h3> 
                <div class="ideas">
                    {% for idea in priority.idea_set.all %}
                        <div class="idea">
                            <h5> {{idea.title}} </h5>
                            <p> {{idea.text}} </p>
                            <h6> {{idea.author}} {{idea.send_date.date}} </h6>
                        </div>
                    {% endfor %}
                </div>

                <button data-toggle="modal" type="button" class="btn btn-secondary priority_container__form-button" 
                            data-target="#modal_id_{{priority.priority}}" >
                    <h5>Add task</h5> 
                </button>
                {% include "modals/form_modal.html" with modal_id=priority.priority modal_title=priority.title modal_form_sufix_id=priority.priority modal_redirect_title="Add" %}

            </div>
        {% endfor %}

        {% if modal_form_error_id %}
            <script type="text/javascript">
                $("#{{modal_form_error_id}}").modal('show');
            </script>

        {% endif %}
    </div>

    
{% endblock%}

templates/root/index.html
{% extends "base.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static "css/root/index.css" %}"/>
    <script src="{% static "root/index.js" %}"></script>
{% endblock %}

{% block header %}

    <div class="header">
        {% if user.is_authenticated %}
            <button type="button" class="btn btn-outline-secondary"><a href="{% url "root:logout" %}">Logout</a></button>
            <button type="button" class="btn btn-outline-secondary"><a href=".">Settings</a></button>
            <button type="button" class="btn btn-outline-secondary"><a href="{% url "root:ideas"%}"> Ideas <a></button>
        {% else %}
            <button type="button" class="btn btn-outline-secondary"><a href="{% url "root:login" %}">Sign In</a></button>
            <button type="button" class="btn btn-outline-secondary"><a href="{% url "root:sign_up" %}">sign up</a></button>
        {% endif %}
    </div>

{% endblock %}

{% block main %}
    <div class="main grid-system">
        <div class="left">
            <h3 class="subheader"> Public workspaces </h3>
            {% for workspace in public_workspaces %}

                {% if workspace.password %}
                    <a href="{% url "workspace:workspace" workspace.slug %}">
                        <p>
                            {{ workspace.name }}
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        </p>
                    </a>

                {% else %}
                    <a href="{% url "workspace:workspace" workspace.slug %}"><p>{{ workspace.name }}</p></a>
                {% endif %}

            {% endfor %}

            {% if user.is_authenticated %}
                <button id="hidden_workspace" type="button" class="btn btn-secondary" data-toggle="modal"
                        data-target="#modal_id_">
                    Join to hidden workspace
                </button>

            {% endif %}
        </div>
        <div class="right">
            {% if user.is_authenticated %}
                <h3 class="subheader"> Your Workspaces </h3>
                {% for workspace in allowed_workspaces %}
                    <a href="{% url "workspace:workspace" workspace.slug %}"><p>{{ workspace.name }}</p></a>
                {% endfor %}
            {% else %}
                <h1> I'm currently rewriting this chat-app to react and django rest api.</h1>
            {% endif %}
        </div>
    </div>

    {% include "modals/form_modal.html"  with modal_id="" modal_title="Hidden Workspace" modal_form_id="modal_form_id" modal_form=form modal_form_url=url modal_redirect_title="Join to hidden workspace" %}
    {% if form.errors %}
        <script type="text/javascript">
            $("#modal_id_").modal('show');
        </script>
    {% endif %}
  




{% endblock %}

templates/root/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head %}

{% endblock %}

{% block header %}
    <div class="header d-flex justify-content-center">
        {% if next %}
            {% if user.is_authenticated %}
                <h3>Your account doesn't have access to this page. To proceed,
                    please login with an account that has access.</h3>
            {% else %}
                <h3>Please login to see this page.</h3>
            {% endif %}

        {% else %}
            <h3> Login site</h3>

        {% endif %}
    </div>
{% endblock %}

{% block main %}

    <div class="main d-flex justify-content-center">

        <div class="w-25">
            <form method="post" action="{% url 'root:login' %}">
                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-secondary">Login</button>
                <input type="hidden" name="next" value="{{ next }}">
            </form>
        </div>
    </div>


{% endblock %}

templates/root/sign_up.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head %}

{% endblock %}

{% block header %}
    <div class="header d-flex justify-content-center">
        <h3> Sign up site</h3>
    </div>

{% endblock %}


{% block main %}
    <div class="main d-flex justify-content-center">

        <form action={% url "root:sign_up" %} method="post">
            {% csrf_token %}
            {{ form|crispy}}
            <button type="submit" class="btn btn-secondary">Submit</button>
        </form>
    </div>
{% endblock %}